# This is a sample deployment manifest file for a simple java application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-app
  labels:
    app: java-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-spring-app
  template:
    metadata:
      labels:
        app: java-spring-app
    spec:
      containers:
      - name: java-spring-app
        image: agadhave/spring_app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
