# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: java-spring-app
  labels:
    app: java-spring-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: java-spring-app
  type: NodePort
