name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  docker-build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:${{ github.run_id }}

  update-helm-chart:
    name: Update Helm Chart with New Tag
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Helm Chart Tag
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/java-spring-app-chart/values.yaml

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "freelanceagdevops@gmail.com"
          git config --global user.name "freelanceagdevops"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/freelanceagdevops/Java-Spring-App.git
          git add helm/java-spring-app-chart/values.yaml
          git diff --cached --exit-code || git commit -m "Update Helm chart with tag ${{ github.run_id }}"
          git push
