name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  build-java-app:
    name: Build and Test Java Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and package application
        run: mvn clean package

      - name: Run tests
        run: mvn test

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Run Checkstyle
        run: mvn checkstyle:check
